// xwiki-platform-core/xwiki-platform-node/src/main/node/editors/blocknote-react/src/components/SearchBox.tsx
/**
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
import { DepsContainerContext } from "../contexts";
import { Combobox, InputBase, Paper, useCombobox } from "@mantine/core";
import { t } from "i18next";
import { debounce } from "lodash-es";
import { useCallback, useContext, useEffect, useState } from "react";
import { RiLink } from "react-icons/ri";
import type { LinkSuggestion } from "../misc/linkSuggest";
import type { ModelReferenceParserProvider } from "@xwiki/platform-model-reference-api";
import type { RemoteURLSerializerProvider } from "@xwiki/platform-model-remote-url-api";
import type { KeyboardEvent, ReactElement } from "react";

export type SearchBoxProps = {
  /**
   * The search box's initial value
   */
  initialValue?: string;

  /**
   * The search box's placeholder (when empty)
   */
  placeholder: string;

  /**
   * Perform a search
   *
   * @param query - A user query (text)
   *
   * @returns Suggestions matching the provided query
   */
  getSuggestions: (query: string) => Promise<LinkSuggestion[] | false>;

  /**
   * Render a single suggestion
   *
   * @param suggestion -
   *
   * @returns A JSX element
   */
  renderSuggestion: (suggestion: LinkSuggestion) => ReactElement;

  /**
   * Triggered when a result is selected in the list of suggestions
   */
  onSelect: (url: string) => void;

  /**
   * Triggered when a result is submitted by the user
   *
   * e.g. when the user uses the `<Enter>` key on an URL
   */
  onSubmit: (url: string) => void;
};

/**
 * This component provides a search (text) field with a dropdown for the results
 *
 * Raw URLs input is supported, as well as raw entity references.
 *
 * @see SearchBoxProps
 */
// eslint-disable-next-line max-statements
export const SearchBox: React.FC<SearchBoxProps> = ({
  initialValue,
  placeholder,
  getSuggestions,
  renderSuggestion,
  onSelect,
  onSubmit,
}) => {
  const depsContainer = useContext(DepsContainerContext)!;

  const modelReferenceParser = depsContainer
    .get<ModelReferenceParserProvider>("ModelReferenceParserProvider")
    .get()!;

  const remoteURLSerializer = depsContainer
    .get<RemoteURLSerializerProvider>("RemoteURLSerializerProvider")
    .get()!;

  const combobox = useCombobox({
    onDropdownClose: () => combobox.resetSelectedOption(),
  });

  const [query, setQuery] = useState(initialValue ?? "");
  const [suggestions, setSuggestions] = useState<
    | { status: "loading" }
    | {
        status: "resolved";
        suggestions: LinkSuggestion[];
      }
    | {
        status: "backendSearchUnsupported";
      }
  >({ status: "resolved", suggestions: [] });

  const isUrl = (value: string) =>
    value.startsWith("http://") || value.startsWith("https://");

  const performSearch = useCallback(
    debounce((search: string) => {
      if (isUrl(search)) {
        setSuggestions({ status: "resolved", suggestions: [] });
        return;
      }

      setSuggestions({ status: "loading" });

      // eslint-disable-next-line promise/catch-or-return
      getSuggestions(search).then((suggestions) => {
        setSuggestions(
          // eslint-disable-next-line promise/always-return
          suggestions !== false
            ? { status: "resolved", suggestions }
            : { status: "backendSearchUnsupported" },
        );
      });
    }),
    [setSuggestions, getSuggestions],
  );

  const submitRawValue = useCallback(
    // eslint-disable-next-line max-statements
    async (e: KeyboardEvent<HTMLInputElement>, value: string) => {
      if (isUrl(value)) {
        onSubmit(value);
        return;
      }

      if (!modelReferenceParser || !remoteURLSerializer) {
        e.preventDefault();
        return;
      }

      const reference = await modelReferenceParser
        .parseAsync(value)
        .catch(() => null);

      if (!reference) {
        e.preventDefault();
        return;
      }

      const url = remoteURLSerializer.serialize(reference);

      if (url === undefined) {
        e.preventDefault();
        throw new Error("Failed to serialize entity reference: " + value);
      }

      onSubmit(url);
    },
    [onSubmit, modelReferenceParser, remoteURLSerializer],
  );

  // Automatically perform a search when the query changes
  useEffect(() => performSearch(query), [query, performSearch]);

  // Perform a search at the opening
  useEffect(() => performSearch(""), []);

  return (
    <Combobox
      store={combobox}
      // We don't use a portal as BlockNote's toolbar closes on interaction with an element that isn't part of it in the DOM
      withinPortal={false}
      onOptionSubmit={(url) => {
        if (
          suggestions.status === "loading" ||
          suggestions.status === "backendSearchUnsupported"
        ) {
          return;
        }

        const result = suggestions.suggestions.find((s) => s.url === url);

        if (!result) {
          return;
        }

        combobox.closeDropdown();
        setQuery(result.title);
        onSelect(url);
      }}
    >
      <Combobox.Target>
        <InputBase
          leftSection={<RiLink />}
          rightSection=" "
          placeholder={placeholder}
          value={query}
          onChange={(event) => {
            combobox.openDropdown();
            combobox.updateSelectedOptionIndex();
            setQuery(event.currentTarget.value);
          }}
          onClick={() => combobox.openDropdown()}
          onFocus={() => combobox.openDropdown()}
          onBlur={() => {
            combobox.closeDropdown();
          }}
          onKeyDown={(e) =>
            e.key === "Enter" && submitRawValue(e, e.currentTarget.value)
          }
        />
      </Combobox.Target>

      {
        // Don't display results for URLs
        !isUrl(query) &&
          // Don't display results if the query is empty and we have no results
          (query.length > 0 ||
            suggestions.status === "loading" ||
            (suggestions.status === "resolved" &&
              suggestions.suggestions.length > 0)) && (
            <Combobox.Dropdown
              style={{
                zIndex: 10000,
              }}
            >
              <Paper shadow="md" p="sm">
                <Combobox.Options>
                  {suggestions.status === "loading" ? (
                    <Combobox.Empty>
                      {t("blocknote.combobox.loadingSuggestions")}
                    </Combobox.Empty>
                  ) : suggestions.status === "backendSearchUnsupported" ? (
                    <Combobox.Empty>
                      {t("blocknote.combobox.backendSearchUnsupported")}
                    </Combobox.Empty>
                  ) : suggestions.suggestions.length > 0 ? (
                    suggestions.suggestions.map((suggestion) => (
                      <Combobox.Option
                        value={suggestion.url}
                        key={suggestion.url}
                      >
                        {renderSuggestion(suggestion)}
                      </Combobox.Option>
                    ))
                  ) : (
                    <Combobox.Empty>
                      {t("blocknote.combobox.noResultFound")}
                    </Combobox.Empty>
                  )}
                </Combobox.Options>
              </Paper>
            </Combobox.Dropdown>
          )
      }
    </Combobox>
  );
};

// xwiki-platform-core/xwiki-platform-node/src/main/node/core/link-modal/link-modal-ui/src/vue/SearchBox.vue
<!--
  See the NOTICE file distributed with this work for additional
  information regarding copyright ownership.

  This is free software; you can redistribute it and/or modify it
  under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation; either version 2.1 of
  the License, or (at your option) any later version.

  This software is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this software; if not, write to the Free
  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA, or see the FSF site: http://www.fsf.org.
-->
<script type="module" lang="ts">
type SearchLinkSuggestion<T, U> = {
  value: T;
  renderingData: U;
  key: string;
  equivalentQuery: string;
};

type SearchLinkSuggestor<T, U> = (
  query: string,
) => Promise<SearchLinkSuggestion<T, U>[] | false>;

export type { SearchLinkSuggestion, SearchLinkSuggestor };
</script>

<script setup lang="ts" generic="T, U">
import { debounce } from "lodash-es";
import { ref, shallowRef, watch } from "vue";

const { initialValue, getSuggestions, trySubmitRaw } = defineProps<{
  /**
   * Input field label
   */
  label: string;

  /**
   * The search box's initial value
   */
  initialValue: string | null;

  /**
   * The search box's placeholder (when empty)
   */
  placeholder?: string;

  /**
   * Perform a search
   *
   * @param query - A user query (text)
   *
   * @returns Suggestions matching the provided query
   */
  getSuggestions: SearchLinkSuggestor<T, U>;

  /**
   * Triggered when the user tries to submit a raw input (e.g. an URL)
   *
   * @param raw - The raw input text field
   *
   * @returns `true` in case of valid input, `false` to keep the list open
   */
  trySubmitRaw?: (raw: string) => boolean;
}>();

defineSlots<{
  /**
   * Render a single suggestion
   */
  renderSuggestion(suggestion: SearchLinkSuggestion<T, U>): unknown;
}>();

const emit = defineEmits<{
  /**
   * Triggered when a result is selected in the list of suggestions
   */
  select: [suggestion: T];
}>();

const query = ref(initialValue ?? "");

// When programatically updating `query` (e.g. after the user selected a suggestion),
// this trigger prevents the query watcher from performing a new search (which would be pointless)
const justDynamicallyUpdatedQuery = ref(false);

const suggestions = shallowRef<
  | { status: "loading" }
  | {
      status: "resolved";
      results: SearchLinkSuggestion<T, U>[];
    }
  | {
      status: "backendSearchUnsupported";
    }
>({ status: "resolved", results: [] });

const performSearch = debounce(async (search: string) => {
  suggestions.value = { status: "loading" };

  const results = await getSuggestions(search);

  suggestions.value =
    results === false
      ? { status: "backendSearchUnsupported" }
      : { status: "resolved", results: results };
});

function selectSuggestion(suggestion: SearchLinkSuggestion<T, U>): void {
  console.log(suggestion);
  justDynamicallyUpdatedQuery.value = true;
  query.value = suggestion.equivalentQuery;
  closeSuggestions();
  emit("select", suggestion.value);
}

function closeSuggestions(): void {
  if (suggestions.value.status === "resolved") {
    suggestions.value = { status: "resolved", results: [] };
  }
}

// eslint-disable-next-line max-statements
function focusRelativeSuggestion(relativeIdx: number): void {
  if (suggestions.value.status !== "resolved") {
    return;
  }

  const { results } = suggestions.value;

  if (results.length === 0) {
    return;
  }

  if (focusedSuggestionKey.value === null) {
    focusedSuggestionKey.value = results[0].key;
    return;
  }

  const currIndex = results.findIndex(
    (sugg) => sugg.key === focusedSuggestionKey.value,
  );

  if (currIndex === -1) {
    focusedSuggestionKey.value = results[0].key;
    return;
  }

  if (
    currIndex + relativeIdx >= 0 &&
    currIndex + relativeIdx < results.length
  ) {
    focusedSuggestionKey.value = results[currIndex + relativeIdx].key;
  }
}

const focusedSuggestionKey = ref<string | null>(null);

function onEnterKey(): void {
  if (focusedSuggestionKey.value !== null) {
    if (suggestions.value.status !== "resolved") {
      throw new Error(
        "Internal error: suggestions not resolved while focused suggestion key set",
      );
    }

    const suggestion = suggestions.value.results.find(
      (sugg) => sugg.key === focusedSuggestionKey.value,
    );

    if (!suggestion) {
      throw new Error("Internal error: focused suggestion not found");
    }

    selectSuggestion(suggestion);
  } else if (trySubmitRaw?.(query.value)) {
    closeSuggestions();
  }
}

watch(query, (query) => {
  if (justDynamicallyUpdatedQuery.value) {
    justDynamicallyUpdatedQuery.value = false;
    return;
  }

  performSearch(query);
});

watch(suggestions, (suggestions) => {
  focusedSuggestionKey.value =
    suggestions.status === "resolved" && suggestions.results.length > 0
      ? suggestions.results[0].key
      : null;
});
</script>

<template>
  <div>
    <x-text-field
      :label
      :placeholder
      v-model="query"
      @keydown.enter.prevent="onEnterKey()"
      @keydown.up.prevent="focusRelativeSuggestion(-1)"
      @keydown.down.prevent="focusRelativeSuggestion(+1)"
      @focus="performSearch(query)"
      @blur="closeSuggestions()"
    />

    <div class="suggestions">
      <h3
        class="status-message"
        v-if="suggestions.status === 'backendSearchUnsupported'"
      >
        Backend search is unsupported.
      </h3>

      <h3 class="status-message" v-if="suggestions.status === 'loading'">
        Loading...
      </h3>

      <!-- NOTE: `@mousedown.prevent` prevents the `blur` event from the query `input` field above to trigger *before*
                  the suggestions' `click` handler -->
      <ul
        class="suggestions"
        @mousedown.prevent
        v-if="suggestions.status === 'resolved'"
      >
        <li
          v-for="suggestion in suggestions.results"
          :key="suggestion.key"
          class="suggestion"
          :class="focusedSuggestionKey === suggestion.key ? ['focused'] : []"
          @click="selectSuggestion(suggestion)"
          @mouseenter="focusedSuggestionKey = suggestion.key"
          @mouseleave="
            if (focusedSuggestionKey === suggestion.key) {
              focusedSuggestionKey = null;
            }
          "
        >
          <slot name="renderSuggestion" v-bind="suggestion">
            <em>Missing suggestion rendering slot</em>
          </slot>
        </li>
      </ul>
    </div>
  </div>
</template>

<style>
.status-message {
  color: darkgray;
}

.suggestions {
  padding: 0rem 0.5rem;
  list-style-type: none;
}

.suggestion {
  padding: 0.5rem;
  border-radius: 0.5rem;
  cursor: pointer;

  &.focused {
    background-color: lightgray;
  }
}
</style>
